[vars]
path1 = "some/path"
path2 = "example/path"
path3 = "test/path"

[rules]
service1 = "cargo run --manifest-path {path1}"
service2 = "cargo run --manifest-path {path2}"
service3 = "cargo run --manifest-path {path3}"

[run]
thread1 = ["service1", "service2"]
thread2 = ["service3"]
